version: '3'
services:
  mysql-db:
    container_name: mysql-docker-local        # 指定容器的名称
    image: mysql:5.7                   # 指定镜像和版本
    ports:
      - 5306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root                      #密码
     # MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
#    volumes:
#      - "D:\docker\mysql\data:/var/lib/mysql"           # 挂载数据目录
#      - "${MYSQL_DIR}/config:/etc/mysql/conf.d"      # 挂载配置文件目录
  redis:
    # 指定镜像
    container_name: redis-docker-local
    image: redis:latest
    ports:
      # 端口映射
      - 9379:6379
#    volumes:
#      # 目录映射
#      - "${REDIS_DIR}/conf:/usr/local/etc/redis"
#      - "${REDIS_DIR}/data:/data"
    command:
      # 执行的命令
      redis-server

  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone-local
    environment:
      - MODE=standalone
    volumes:
      - D:\docker\nacos-compose\logs:/home/nacos/logs
    ports:
      - 8848:8848

  zookeeper:
    container_name: zookeeper-docker-local
    image: zookeeper
    ports:
      - 2181:2181
  dubbo-admin:
    container_name: dubbo-admin-docker-local
    image: apache/dubbo-admin
    ports:
      - 8888:8080
    environment:
      - admin.registry.address=zookeeper://zookeeper:2181
      - admin.config-center=zookeeper://zookeeper:2181
      - admin.metadata-report.address=zookeeper://zookeeper:2181